# Get Financial Data from API and Send to Snowflake

In [58]:
# Load modules
import pandas as pd
import os
import requests
import json
import datetime as dt
import pandas as pd
from time import sleep
import os
from ..credentials import credentials

ImportError: attempted relative import with no known parent package

In [11]:
# Get currency codes available in API 
file_path = '../data/currencies/currencies.json' # From website
df = pd.read_json(file_path)

currencies = ""
for a in df['code'].values:
    currencies += a + ","

print(currencies)

AED,AFN,ALL,AMD,ANG,AOA,ARS,AUD,AWG,AZN,BAM,BBD,BDT,BGN,BHD,BIF,BMD,BND,BOB,BRL,BSD,BTC,BTN,BWP,BYN,BYR,BZD,CAD,CDF,CHF,CLF,CLP,CNY,COP,CRC,CUC,CUP,CVE,CZK,DJF,DKK,DOP,DZD,EEK,EGP,ERN,ETB,EUR,FJD,FKP,GBP,GEL,GGP,GHS,GIP,GMD,GNF,GTQ,GYD,HKD,HNL,HRK,HTG,HUF,IDR,ILS,IMP,INR,IQD,IRR,ISK,JEP,JMD,JOD,JPY,KES,KGS,KHR,KMF,KPW,KRW,KWD,KYD,KZT,LAK,LBP,LKR,LRD,LSL,LTL,LVL,LYD,MAD,MDL,MGA,MKD,MMK,MNT,MOP,MRO,MUR,MVR,MWK,MXN,MYR,MZN,NAD,NGN,NIO,NOK,NPR,NZD,OMR,PAB,PEN,PGK,PHP,PKR,PLN,PYG,QAR,RON,RSD,RUB,RWF,SAR,SBD,SCR,SDG,SEK,SGD,SHP,SLL,SOS,SRD,STD,SVC,SYP,SZL,THB,TJS,TMT,TND,TOP,TRY,TTD,TWD,TZS,UAH,UGX,USD,UYU,UZS,VEF,VND,VUV,WST,XAF,XAG,XAU,XCD,XDR,XOF,XPF,YER,ZAR,ZMK,ZMW,ZWL,

In [18]:
import credentials

# API URL
url = 'http://api.currencylayer.com/historical'

# 500 days
start_date = dt.date(2011, 1, 1)
end_date = dt.date(2012, 5, 15)
delta = dt.timedelta(days=1)

# Loop through each day and get conversion rates to USD for every currency
data = []
while start_date <= end_date:
    print(start_date)
    
    params = {
        'access_key' : os.getenv('API_KEY'),
        'source' : 'USD',
        'currencies' : currencies,
        'date' : start_date
    }

    response = requests.get(url, params=params)

    if response.status_code == 200:
        json_data = response.json()
        data.append(json_data)
    else:
        print('Error connecting to the API.')
        print(response)

    start_date += delta

    sleep(1)

print(pd.json_normalize(data))

2011-01-01
2011-01-02
2011-01-03
2011-01-04
2011-01-05
2011-01-06
2011-01-07
2011-01-08
2011-01-09
2011-01-10
2011-01-11
2011-01-12
2011-01-13
2011-01-14
2011-01-15
2011-01-16
2011-01-17
2011-01-18
2011-01-19
2011-01-20
2011-01-21
2011-01-22
2011-01-23
2011-01-24
2011-01-25
2011-01-26
2011-01-27
2011-01-28
2011-01-29
2011-01-30
2011-01-31
2011-02-01
2011-02-02
2011-02-03
2011-02-04
2011-02-05
2011-02-06
2011-02-07
2011-02-08
2011-02-09
2011-02-10
2011-02-11
2011-02-12
2011-02-13
2011-02-14
2011-02-15
2011-02-16
2011-02-17
2011-02-18
2011-02-19
2011-02-20
2011-02-21
2011-02-22
2011-02-23
2011-02-24
2011-02-25
2011-02-26
2011-02-27
2011-02-28
2011-03-01
2011-03-02
2011-03-03
2011-03-04
2011-03-05
2011-03-06
2011-03-07
2011-03-08
2011-03-09
2011-03-10
2011-03-11
2011-03-12
2011-03-13
2011-03-14
2011-03-15
2011-03-16
2011-03-17
2011-03-18
2011-03-19
2011-03-20
2011-03-21
2011-03-22
2011-03-23
2011-03-24
2011-03-25
2011-03-26
2011-03-27
2011-03-28
2011-03-29
2011-03-30
2011-03-31
2011-04-01
2011-04-02
2011-04-03
2011-04-04
2011-04-05
2011-04-06
2011-04-07
2011-04-08
2011-04-09
2011-04-10
2011-04-11
2011-04-12
2011-04-13
2011-04-14
2011-04-15
2011-04-16
2011-04-17
2011-04-18
2011-04-19
2011-04-20
2011-04-21
2011-04-22
2011-04-23
2011-04-24
2011-04-25
2011-04-26
2011-04-27
2011-04-28
2011-04-29
2011-04-30
2011-05-01
2011-05-02
2011-05-03
2011-05-04
2011-05-05
2011-05-06
2011-05-07
2011-05-08
2011-05-09
2011-05-10
2011-05-11
2011-05-12
2011-05-13
2011-05-14
2011-05-15
2011-05-16
2011-05-17
2011-05-18
2011-05-19
2011-05-20
2011-05-21
2011-05-22
2011-05-23
2011-05-24
2011-05-25
2011-05-26
2011-05-27
2011-05-28
2011-05-29
2011-05-30
2011-05-31
2011-06-01
2011-06-02
2011-06-03
2011-06-04
2011-06-05
2011-06-06
2011-06-07
2011-06-08
2011-06-09
2011-06-10
2011-06-11
2011-06-12
2011-06-13
2011-06-14
2011-06-15
2011-06-16
2011-06-17
2011-06-18
2011-06-19
2011-06-20
2011-06-21
2011-06-22
2011-06-23
2011-06-24
2011-06-25
2011-06-26
2011-06-27
2011-06-28
2011-06-29
2011-06-30
2011-07-01
2011-07-02
2011-07-03
2011-07-04
2011-07-05
2011-07-06
2011-07-07
2011-07-08
2011-07-09
2011-07-10
2011-07-11
2011-07-12
2011-07-13
2011-07-14
2011-07-15
2011-07-16
2011-07-17
2011-07-18
2011-07-19
2011-07-20
2011-07-21
2011-07-22
2011-07-23
2011-07-24
2011-07-25
2011-07-26
2011-07-27
2011-07-28
2011-07-29
2011-07-30
2011-07-31
2011-08-01
2011-08-02
2011-08-03
2011-08-04
2011-08-05
2011-08-06
2011-08-07
2011-08-08
2011-08-09
2011-08-10
2011-08-11
2011-08-12
2011-08-13
2011-08-14
2011-08-15
2011-08-16
2011-08-17
2011-08-18
2011-08-19
2011-08-20
2011-08-21
2011-08-22
2011-08-23
2011-08-24
2011-08-25
2011-08-26
2011-08-27
2011-08-28
2011-08-29
2011-08-30
2011-08-31
2011-09-01
2011-09-02
2011-09-03
2011-09-04
2011-09-05
2011-09-06
2011-09-07
2011-09-08
2011-09-09
2011-09-10
2011-09-11
2011-09-12
2011-09-13
2011-09-14
2011-09-15
2011-09-16
2011-09-17
2011-09-18
2011-09-19
2011-09-20
2011-09-21
2011-09-22
2011-09-23
2011-09-24
2011-09-25
2011-09-26
2011-09-27
2011-09-28
2011-09-29
2011-09-30
2011-10-01
2011-10-02
2011-10-03
2011-10-04
2011-10-05
2011-10-06
2011-10-07
2011-10-08
2011-10-09
2011-10-10
2011-10-11
2011-10-12
2011-10-13
2011-10-14
2011-10-15
2011-10-16
2011-10-17
2011-10-18
2011-10-19
2011-10-20
2011-10-21
2011-10-22
2011-10-23
2011-10-24
2011-10-25
2011-10-26
2011-10-27
2011-10-28
2011-10-29
2011-10-30
2011-10-31
2011-11-01
2011-11-02
2011-11-03
2011-11-04
2011-11-05
2011-11-06
2011-11-07
2011-11-08
2011-11-09
2011-11-10
2011-11-11
2011-11-12
2011-11-13
2011-11-14
2011-11-15
2011-11-16
2011-11-17
2011-11-18
2011-11-19
2011-11-20
2011-11-21
2011-11-22
2011-11-23
2011-11-24
2011-11-25
2011-11-26
2011-11-27
2011-11-28
2011-11-29
2011-11-30
2011-12-01
2011-12-02
2011-12-03
2011-12-04
2011-12-05
2011-12-06
2011-12-07
2011-12-08
2011-12-09
2011-12-10
2011-12-11
2011-12-12
2011-12-13
2011-12-14
2011-12-15
2011-12-16
2011-12-17
2011-12-18
2011-12-19
2011-12-20
2011-12-21
2011-12-22
2011-12-23
2011-12-24
2011-12-25
2011-12-26
2011-12-27
2011-12-28
2011-12-29
2011-12-30
2011-12-31
2012-01-01
2012-01-02
2012-01-03
2012-01-04
2012-01-05
2012-01-06
2012-01-07
2012-01-08
2012-01-09
2012-01-10
2012-01-11
2012-01-12
2012-01-13
2012-01-14
2012-01-15
2012-01-16
2012-01-17
2012-01-18
2012-01-19
2012-01-20
2012-01-21
2012-01-22
2012-01-23
2012-01-24
2012-01-25
2012-01-26
2012-01-27
2012-01-28
2012-01-29
2012-01-30
2012-01-31
2012-02-01
2012-02-02
2012-02-03
2012-02-04
2012-02-05
2012-02-06
2012-02-07
2012-02-08
2012-02-09
2012-02-10
2012-02-11
2012-02-12
2012-02-13
2012-02-14
2012-02-15
2012-02-16
2012-02-17
2012-02-18
2012-02-19
2012-02-20
2012-02-21
2012-02-22
2012-02-23
2012-02-24
2012-02-25
2012-02-26
2012-02-27
2012-02-28
2012-02-29
2012-03-01
2012-03-02
2012-03-03
2012-03-04
2012-03-05
2012-03-06
2012-03-07
2012-03-08
2012-03-09
2012-03-10
2012-03-11
2012-03-12
2012-03-13
2012-03-14
2012-03-15
2012-03-16
2012-03-17
2012-03-18
2012-03-19
2012-03-20
2012-03-21
2012-03-22
2012-03-23
2012-03-24
2012-03-25
2012-03-26
2012-03-27
2012-03-28
2012-03-29
2012-03-30
2012-03-31
2012-04-01
2012-04-02
2012-04-03
2012-04-04
2012-04-05
2012-04-06
2012-04-07
2012-04-08
2012-04-09
2012-04-10
2012-04-11
2012-04-12
2012-04-13
2012-04-14
2012-04-15
2012-04-16
2012-04-17
2012-04-18
2012-04-19
2012-04-20
2012-04-21
2012-04-22
2012-04-23
2012-04-24
2012-04-25
2012-04-26
2012-04-27
2012-04-28
2012-04-29
2012-04-30
2012-05-01
2012-05-02
2012-05-03
2012-05-04
2012-05-05
2012-05-06
2012-05-07
2012-05-08
2012-05-09
2012-05-10
2012-05-11
2012-05-12
2012-05-13
2012-05-14
2012-05-15
     success                            terms  \
0       True  https://currencylayer.com/terms
1       True  https://currencylayer.com/terms
2       True  https://currencylayer.com/terms
3       True  https://currencylayer.com/terms
4       True  https://currencylayer.com/terms
..       ...                              ...
496     True  https://currencylayer.com/terms
497     True  https://currencylayer.com/terms
498     True  https://currencylayer.com/terms
499     True  https://currencylayer.com/terms
500     True  https://currencylayer.com/terms

                               privacy  historical        date   timestamp  \
0    https://currencylayer.com/privacy        True  2011-01-01  1293926399
1    https://currencylayer.com/privacy        True  2011-01-02  1294012799
2    https://currencylayer.com/privacy        True  2011-01-03  1294099199
3    https://currencylayer.com/privacy        True  2011-01-04  1294185599
4    https://currencylayer.com/privacy        True  2011-01-05  1294271999
..                                 ...         ...         ...         ...
496  https://currencylayer.com/privacy        True  2012-05-11  1336780799
497  https://currencylayer.com/privacy        True  2012-05-12  1336867199
498  https://currencylayer.com/privacy        True  2012-05-13  1336953599
499  https://currencylayer.com/privacy        True  2012-05-14  1337039999
500  https://currencylayer.com/privacy        True  2012-05-15  1337126399

    source  quotes.USDAED  quotes.USDAFN  quotes.USDALL  ...  quotes.USDWST  \
0      USD       3.672725      43.022128     104.575010  ...       2.336720
1      USD       3.672725      43.022128     104.575010  ...       2.336720
2      USD       3.672725      43.022943     104.066656  ...       2.323108
3      USD       3.672725      43.024901     103.971710  ...       2.324942
4      USD       3.672750      43.025054     105.042514  ...       2.314017
..     ...            ...            ...            ...  ...            ...
496    USD       3.672800      48.282905     107.765055  ...       2.278141
497    USD       3.672800      48.282905     107.765055  ...       2.278141
498    USD       3.672800      48.282905     107.765055  ...       2.278141
499    USD       3.672775      48.318881     108.301126  ...       2.353049
500    USD       3.672800      48.300105     108.440791  ...       2.389667

     quotes.USDXAF  quotes.USDXCD  quotes.USDXDR  quotes.USDXOF  \
0       498.506150       2.691726       0.649095     493.006150
1       498.506150       2.691726       0.649095     493.006150
2       498.763595       2.692805       0.649507     491.588590
3       497.427101       2.692677       0.646749     489.377096
4       501.274103       2.691924       0.649073     497.949103
..             ...            ...            ...            ...
496     507.294941       2.700379       0.650663     507.007649
497     507.294941       2.700379       0.650663     507.007649
498     507.294941       2.700379       0.650663     507.007649
499     510.741858       2.700027       0.651859     510.203238
500     513.027615       2.699770       0.652248     512.625302

     quotes.USDXPF  quotes.USDYER  quotes.USDZAR  quotes.USDZMK  quotes.USDCLF
0        90.053383     213.871530       6.622288    4797.421008            NaN
1        90.053383     213.871530       6.622288    4797.421008            NaN
2        89.800218     214.269819       6.610463    4789.887081            NaN
3        89.417082     214.274582       6.665823    4782.497459            NaN
4        90.256929     214.573460       6.729875    4737.504560            NaN
..             ...            ...            ...            ...            ...
496      92.310373     213.939156       8.094300    5125.041402       0.021176
497      92.310373     213.939156       8.097467    5125.041402       0.021176
498      92.310373     213.939156       8.097467    5125.041402       0.021176
499      92.785643     213.595006       8.187947    5209.883191       0.021176
500      93.307875     213.867482       8.236632    5210.758151       0.021176

[501 rows x 160 columns]

In [19]:
# Take a look as df
pd.json_normalize(data)

,success,terms,privacy,historical,date,timestamp,source,quotes.USDAED,quotes.USDAFN,quotes.USDALL,...,quotes.USDWST,quotes.USDXAF,quotes.USDXCD,quotes.USDXDR,quotes.USDXOF,quotes.USDXPF,quotes.USDYER,quotes.USDZAR,quotes.USDZMK,quotes.USDCLF
0,True,https://currencylayer.com/terms,https://currencylayer.com/privacy,True,2011-01-01,1293926399,USD,3.672725,43.022128,104.575010,...,2.336720,498.506150,2.691726,0.649095,493.006150,90.053383,213.871530,6.622288,4797.421008,NaN
1,True,https://currencylayer.com/terms,https://currencylayer.com/privacy,True,2011-01-02,1294012799,USD,3.672725,43.022128,104.575010,...,2.336720,498.506150,2.691726,0.649095,493.006150,90.053383,213.871530,6.622288,4797.421008,NaN
2,True,https://currencylayer.com/terms,https://currencylayer.com/privacy,True,2011-01-03,1294099199,USD,3.672725,43.022943,104.066656,...,2.323108,498.763595,2.692805,0.649507,491.588590,89.800218,214.269819,6.610463,4789.887081,NaN
3,True,https://currencylayer.com/terms,https://currencylayer.com/privacy,True,2011-01-04,1294185599,USD,3.672725,43.024901,103.971710,...,2.324942,497.427101,2.692677,0.646749,489.377096,89.417082,214.274582,6.665823,4782.497459,NaN
4,True,https://currencylayer.com/terms,https://currencylayer.com/privacy,True,2011-01-05,1294271999,USD,3.672750,43.025054,105.042514,...,2.314017,501.274103,2.691924,0.649073,497.949103,90.256929,214.573460,6.729875,4737.504560,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,True,https://currencylayer.com/terms,https://currencylayer.com/privacy,True,2012-05-11,1336780799,USD,3.672800,48.282905,107.765055,...,2.278141,507.294941,2.700379,0.650663,507.007649,92.310373,213.939156,8.094300,5125.041402,0.021176
497,True,https://currencylayer.com/terms,https://currencylayer.com/privacy,True,2012-05-12,1336867199,USD,3.672800,48.282905,107.765055,...,2.278141,507.294941,2.700379,0.650663,507.007649,92.310373,213.939156,8.097467,5125.041402,0.021176
498,True,https://currencylayer.com/terms,https://currencylayer.com/privacy,True,2012-05-13,1336953599,USD,3.672800,48.282905,107.765055,...,2.278141,507.294941,2.700379,0.650663,507.007649,92.310373,213.939156,8.097467,5125.041402,0.021176
499,True,https://currencylayer.com/terms,https://currencylayer.com/privacy,True,2012-05-14,1337039999,USD,3.672775,48.318881,108.301126,...,2.353049,510.741858,2.700027,0.651859,510.203238,92.785643,213.595006,8.187947,5209.883191,0.021176
500,True,https://currencylayer.com/terms,https://currencylayer.com/privacy,True,2012-05-15,1337126399,USD,3.672800,48.300105,108.440791,...,2.389667,513.027615,2.699770,0.652248,512.625302,93.307875,213.867482,8.236632,5210.758151,0.021176

In [20]:
# Save data to file
pd.json_normalize(data).to_json('../data/currencies/forex_history.json')

In [22]:
# Read data from file
source_df = pd.read_json('../data/currencies/forex_history.json')
input_json_data = data

In [26]:
# Currencies is a single string
currencies

'AED,AFN,ALL,AMD,ANG,AOA,ARS,AUD,AWG,AZN,BAM,BBD,BDT,BGN,BHD,BIF,BMD,BND,BOB,BRL,BSD,BTC,BTN,BWP,BYN,BYR,BZD,CAD,CDF,CHF,CLF,CLP,CNY,COP,CRC,CUC,CUP,CVE,CZK,DJF,DKK,DOP,DZD,EEK,EGP,ERN,ETB,EUR,FJD,FKP,GBP,GEL,GGP,GHS,GIP,GMD,GNF,GTQ,GYD,HKD,HNL,HRK,HTG,HUF,IDR,ILS,IMP,INR,IQD,IRR,ISK,JEP,JMD,JOD,JPY,KES,KGS,KHR,KMF,KPW,KRW,KWD,KYD,KZT,LAK,LBP,LKR,LRD,LSL,LTL,LVL,LYD,MAD,MDL,MGA,MKD,MMK,MNT,MOP,MRO,MUR,MVR,MWK,MXN,MYR,MZN,NAD,NGN,NIO,NOK,NPR,NZD,OMR,PAB,PEN,PGK,PHP,PKR,PLN,PYG,QAR,RON,RSD,RUB,RWF,SAR,SBD,SCR,SDG,SEK,SGD,SHP,SLL,SOS,SRD,STD,SVC,SYP,SZL,THB,TJS,TMT,TND,TOP,TRY,TTD,TWD,TZS,UAH,UGX,USD,UYU,UZS,VEF,VND,VUV,WST,XAF,XAG,XAU,XCD,XDR,XOF,XPF,YER,ZAR,ZMK,ZMW,ZWL,'

In [39]:
currency_list = currencies.split(',')

In [48]:
# create the data for the columns we want to convert to rows.
value_vars = ["USD"+code for code in currency_list]

# drop some currencies (not in historical data e.g. BTC)
not_used_vars = ['USD', 'USDBTC', 'USDBYN', 'USDCUC', 'USDCUP', 'USDEEK', 'USDERN', 'USDGGP', 'USDIMP', 'USDJEP', 'USDKYD', 'USDSVC', 'USDUSD', 'USDXAG', 'USDXAU', 'USDZMW', 'USDZWL']
for i in not_used_vars:
    if i in value_vars:
        value_vars.remove(i)
        print(i, 'removed')
    else: 
        print(i, 'not in list')

USD removed
USDBTC removed
USDBYN removed
USDCUC removed
USDCUP removed
USDEEK removed
USDERN removed
USDGGP removed
USDIMP removed
USDJEP removed
USDKYD removed
USDSVC removed
USDUSD removed
USDXAG removed
USDXAU removed
USDZMW removed
USDZWL removed

In [69]:
#Reshape de DataFrame to get the wanted value
df_melted = pd.melt(df, id_vars=['timestamp', 'date'], value_vars=value_vars, value_name = 'value_to_dollar')

#We replace the CODE for the id of the currency.
df_melted.rename(columns={'variable':'currency_id'}, inplace=True)

currencies_dict_changed = {"USD"+code for code in currencies}

df_melted['currency_id'] = df_melted['currency_id'].replace(r'USD', '', regex=True)

df_melted.rename(columns={"currency_id": "currency_code"}, inplace=True)
display(df_melted)

        timestamp        date currency_code  value_to_dollar
0      1293926399  2011-01-01           AED         3.672725
1      1294012799  2011-01-02           AED         3.672725
2      1294099199  2011-01-03           AED         3.672725
3      1294185599  2011-01-04           AED         3.672725
4      1294271999  2011-01-05           AED         3.672750
...           ...         ...           ...              ...
76648  1336780799  2012-05-11           ZMK      5125.041402
76649  1336867199  2012-05-12           ZMK      5125.041402
76650  1336953599  2012-05-13           ZMK      5125.041402
76651  1337039999  2012-05-14           ZMK      5209.883191
76652  1337126399  2012-05-15           ZMK      5210.758151

[76653 rows x 4 columns]

In [55]:
# Save data
df_melted.to_csv('../data/currencies/forex_history_for_snowflake.csv')
df_melted.to_json('../data/currencies/forex_history_for_snowflake.json')

# SEND CURRENCIES TO SNOWFLAKE

In [157]:
curr_df = pd.read_json('../data/currencies/currencies.json')
curr_df.index += 1
curr_df.head()

  code                           name               country      continent
1  AED    United Arab Emirates Dirham  United Arab Emirates           Asia
2  AFN                 Afghan Afghani           Afghanistan           Asia
3  ALL                   Albanian Lek               Albania         Europe
4  AMD                  Armenian Dram               Armenia           Asia
5  ANG  Netherlands Antillean Guilder  Netherlands Antilles  North America

In [97]:
# Maps to create currency ids
code_to_id = {}
for ix, row in curr_df.iterrows():
    code_to_id[row['code']] = ix

# code_to_id

In [137]:
import credentials
import snowflake.connector

def connect_snowflake():
    conn = snowflake.connector.connect(
        # user=os.getenv('SNOWSQL_USR'), 
        # password=os.getenv('SNOWSQL_PWD'), 
        # account=os.getenv('SNOWSQL_ACC'),
        # warehouse=os.getenv('SNOWSQL_WH'), 
        # database=os.getenv('SNOWSQL_DB'),
        # schema=os.getenv('SNOWSQL_SCH') 
    ) 
    print("Snowflake connection successfully.")
    return conn

In [104]:
curr_df.columns

Index(['code', 'name', 'country', 'continent'], dtype='object')

In [119]:
# Send currency data

for ix, row in curr_df.iterrows():
    connection = connect_snowflake()
    cursor = connection.cursor()

    try:
        query = "INSERT INTO CURRENCIES (C_ID, C_CODE, C_NAME, C_COUNTRY, C_CONTINENT) VALUES (%s, %s, %s, %s, %s)" 
        
        cursor.execute(query, (ix, row['code'], row['name'], row['country'], row['continent']))
        connection.commit()

        print({'message': 'Currencies created successfully'}) 
    except Exception as e:
        print({'error': str(e)})
    finally:
        cursor.close()
        connection.close()

Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}
Snowflake connection successfully.
{'message': 'Currencies created successfully'}

# Send forex history to SF

In [143]:
forex_df = df_melted
forex_df['currency_id'] = forex_df['currency_code'].replace(code_to_id)
forex_df

        timestamp        date currency_code  value_to_dollar  currency_id
0      1293926399  2011-01-01           AED         3.672725            1
1      1294012799  2011-01-02           AED         3.672725            1
2      1294099199  2011-01-03           AED         3.672725            1
3      1294185599  2011-01-04           AED         3.672725            1
4      1294271999  2011-01-05           AED         3.672750            1
...           ...         ...           ...              ...          ...
76648  1336780799  2012-05-11           ZMK      5125.041402          167
76649  1336867199  2012-05-12           ZMK      5125.041402          167
76650  1336953599  2012-05-13           ZMK      5125.041402          167
76651  1337039999  2012-05-14           ZMK      5209.883191          167
76652  1337126399  2012-05-15           ZMK      5210.758151          167

[76653 rows x 5 columns]

In [155]:
# Currency code doesn't go into this table
forex_df_new = forex_df.drop(columns=['currency_code'])
print(len(forex_df_new))

# Remove nulls
forex_df_cleaned = forex_df_new.where(pd.notna(forex_df_new), )
print(len(forex_df_cleaned))
forex_df_filtered = forex_df_cleaned.dropna(subset=['timestamp', 'date', 'currency_id', 'value_to_dollar'])
print(len(forex_df_filtered))
final_list = forex_df_filtered.to_dict(orient='records')

76653
76653
76562

In [156]:
# SEND TO SNOWFLAKE IN BATCHES 

batch_size = 10000  # You can adjust this number based on your specific use case

for i in range(0, len(final_list), batch_size):
    batch = final_list[i:i+batch_size]
    placeholders = ', '.join(['(%s, %s, %s, %s)'] * len(batch))
    query = f"INSERT INTO FOREX_HISTORY (FH_timestamp_id, FH_date, FH_currency_id, FH_value_to_dollar) VALUES {placeholders}"
    
    params = []
    for data in batch:
        params.extend([data['timestamp'], data['date'], data['currency_id'], data['value_to_dollar']])
    
    cursor.execute(query, params)
    connection.commit()

cursor.close()
connection.close()